fragment PostParts on Post {
  __typename
  title
  body
}

fragment NavigationParts on Navigation {
  __typename
  items {
    __typename
    label
    path
    children {
      __typename
      label
      path
    }
  }
}
