[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY = "true"
  NEXT_STATIC_EXPORT = "true"

[functions]
  node_bundler = "esbuild"
  included_files = ["app/api/**"]
  external_node_modules = ["mongodb"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
