[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://botsmann.netlify.app"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
