[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_TINA_CLIENT_ID = "c7fe2362-7424-4956-a241-4d246238f406"
  TINA_TOKEN = "9de4fe3a4f7ddefcf391fdebc4480d4b0a5b0e20"
  TINA_PUBLIC_IS_LOCAL = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
