backend:
  name: git-gateway
  branch: main
  identity_url: "https://botsmann.com/.netlify/identity"
  gateway_url: "https://botsmann.com/.netlify/git/github"
  commit_messages:
    create: "Create {{collection}} "{{slug}}""
    update: "Update {{collection}} "{{slug}}""
    delete: "Delete {{collection}} "{{slug}}""
    uploadMedia: "Upload "{{path}}""
    deleteMedia: "Delete "{{path}}""

# Media and public folders
media_folder: "public/uploads"
public_folder: "/uploads"

# Enable local development
local_backend: true

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "navigation"
    label: "Navigation"
    files:
      - name: "main_nav"
        label: "Main Navigation"
        file: "content/navigation/main.json"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Path", name: "path", widget: "string" }
              - label: "Children"
                name: "children"
                widget: "list"
                required: false
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Path", name: "path", widget: "string" }
