backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "navigation"
    label: "Navigation"
    files:
      - name: "main_nav"
        label: "Main Navigation"
        file: "content/navigation/main.json"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Path", name: "path", widget: "string" }
              - label: "Children"
                name: "children"
                widget: "list"
                required: false
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Path", name: "path", widget: "string" }
